### PR TITLE
attempt to fix manubot compilation issue

### PR DESCRIPTION
**Pull request by emmajhudgins**
removed square bracket syntax around names, added it around links where appropriate

### CODE REVIEW

**Review by Aguncan — COMMENTED** [review]
Seems to be good.

**Review by Aguncan — APPROVED** [review]

**Review by Aguncan — APPROVED** [review]

**Review by Aguncan — COMMENTED** [review]
ok

**Review by Aguncan — APPROVED** [review]

**Comment by emmajhudgins** [comment]
Hey @Aguncan, I think you're having trouble merging this request. Are you having the same problem as #72 ? Otherwise, the button should be active here where it says 'merge pull request':
Screen Shot 2022-01-28 at 5 08 00 PM

**Comment by Aguncan** [comment]
@emmajhudgins You are right.

**Review by Aguncan — APPROVED** [review]

**Review by Aguncan — APPROVED** [review]
OK

**Review by katherinehebert — APPROVED** [review]

**Pull request merged**
