### PR TITLE
General background about GitHub and Git

### PR DESCRIPTION
**Pull request by shafieisabets**
General background about GitHub and Git
A new reference added accordingly.

### CODE REVIEW

**Comment by shafieisabets** [comment]
General background about GitHub and Git.

 
In a study more than 650000 comments, from 130000 issues posted by 64000 developers on GitHub it has been shown that the considered groups play
different roles in a project, communicate differently with different
emotions and level of politeness (five GitHub projects distinguishing contributors between users and developers, and between one-commit and multicommit developers). [@doi:10.1145/3273934.3273943].

**Review by robcrystalornelas — COMMENTED** [review]
@shafieisabets At the moment, I think we need to hold off on incorporating these edits. We have started our detailed review of the intro and all other sections and so we are already chipping away at these sentences. And in general, I think these study you cite is really interesting, but the stats are a bit too details for the first couple of sentences of the paper.

**Comment by shafieisabets** [comment]
@robcrystalornelas  Agree absolutely! Thanks for your comment.
Kind regards
Saeed

**Comment by robcrystalornelas** [comment]
Closing this PR since editing is underway in this section.

**Pull request closed without merging**
