### PR TITLE
Scatterblob

### PR DESCRIPTION
**Pull request by LunaSare**
Addressed feedback points from https://github.com/SORTEE-Github-Hackathon/manuscript/discussions/115 on the scatterblob figure and saved as pdf!

I find that pdf format usually retains the best definition. It could be saved as jpeg but will need to tinker with retina and other resolution parameters.

### CODE REVIEW

**Review by emmajhudgins — APPROVED** [review]
awesome work and detailed code, Luna! Does anyone know how to preview images in the process of reviewing PRs? @pedrohbraga @Aariq @robcrystalornelas

**Comment by robcrystalornelas** [comment]
@emmajhudgins To preview the image, I clicked on the `...` button next to the file and then `view file`. Then I could see the rendered image of the SVG and PDF files

Screen Shot 2022-04-11 at 9 36 15 AM

**Review by robcrystalornelas — APPROVED** [review]
So awesome @LunaSare! I like the changes you made in terms of data visualization moving from _0 to _1. In the figure that ends with _1 I like that everything is a bit more legible and that there's not a big gap between the 'very advanced' and lower difficulties.

I agree with @Aariq that citable and stable code could potentially be moved to something closer to 'low intermediate' depending on what we mean by "stable code".  To me, making code citable is on the easier side, but if we are talking about things like unit testing / continuous integration, then we can leave it as more advanced.

**Comment by emmajhudgins** [comment]
> @emmajhudgins To preview the image, I clicked on the `...` button next to the file and then `view file`. Then I could see the rendered image of the SVG and PDF files
> 
> Screen Shot 2022-04-11 at 9 36 15 AM

Weirdly I can only view the svg, but no problem! As for stable code, maybe we can put it above lab notebooks because it requires external software?

**Comment by LunaSare** [comment]
Yayyy! Thanks everyone for the comments and review! 

I just committed .png and .svg versions of both figures, hopefully that works for everyone.

Re: @Aariq's comment on technical difficulty for "citeable and stable code", this is how I assigned technical difficulty values to each GitHub use:

I created a table where rows are GitHub uses and columns are the tools needed to perform those GitHub uses (it can be GitHub or programming tools).
The table is here https://docs.google.com/spreadsheets/d/1OLBR3M0uV3PMSazWUYHgPeX28wllAgS4PIlJXaNu-2o/edit#gid=0
 
If A GitHub use requires a tool, I assign a number 1 to that cell, if the GitHub use does not requires a tool, I assigned 0 to that cell. At the end I summed values by row to obtain the total number of tools needed to perform each GitHub use.

For example, "Data and code storage" requires knowledge on
- creating GitHub repositories, 
- basic git commands (git pull, git commit, git push)
Then, the technical difficulty for this use will be 2

"Personal Academic work web-log" requires the same tools as "data and code storage", plus
- knowledge of a markup language such as markdown
The technical difficulty for this use will be 3.

For "Citeable and stable code" I considered it required the same tools as  "Personal Academic work web-log", plus:
- creating releases
- managing and creating branches and pull requests
- and, GitHub actions to connect to Zenodo for the DOI
That sums to a technical difficulty of 6.
I guess I am thinking of code that is being maintained through time, hence the branches, pull requests, and releases.

I agree that if we focus on a snapshot of a piece of code that people can cite (for example, code used on a published analysis) we might not even need knowledge of a markup language, as the code would not need formal documentation. That would be a technical difficulty of 3 or 4.

**Comment by Aariq** [comment]
> * and, GitHub actions to connect to Zenodo for the DOI

You don't need to know github actions to connect to Zenodo.  After connecting your GitHub user name to Zenodo you literally just flip a switch and make a release.  To get a citeable DOI for data and/or code you just need to 1) put your code and data in a GitHub repo, 2) flip a switch on Zenodo, 3) make a release, 4) optionally paste markdown for a badge into the README.md

If you navigate to https://zenodo.org/account/settings/github/ there is a brief tutorial.

**Comment by LunaSare** [comment]
Re @robcrystalornelas 
> I agree with @Aariq that citable and stable code could potentially be moved to something closer to 'low intermediate' depending on what we mean by "stable code". To me, making code citable is on the easier side, but if we are talking about things like unit testing / continuous integration, then we can leave it as more advanced.

Re @Aariq 
> Using your spreadsheet I'd put it at a 3---you also do not need to know about branches or PRs. _Qualitatively_, I'd say it's even easier than making a website, which is also at a 3.

Oh yeah, that makes sense! 

So, we could potentially cover the two cases:

By adding "citeable data and code" as a 3., which covers the case of "creating a doi for data and code", and would leave it below "low intermediate" difficulty, right next to "work blogs".

And add something like "Maintaining versioned data and code" that covers the case with a higher difficulty level, that requires unit testing, continuous integration, etc.

What do you think?

**Comment by Aariq** [comment]
> What do you think?
Yeah, that makes sense to me.  The barriers to getting a DOI for your code and data via GitHub are really minimal, so I just didn't want to discourage people from taking advantage of one of the best effort:usefulness use-cases of GitHub.

**Comment by robcrystalornelas** [comment]
@LunaSare I think creating those 2 cases in the figure sounds great to me. 

- Moving the 'citable data and code' down to a 3 in difficulty and keeping the 'maintaining' data and code higher. 
- Separating out the two seems like a good way to move forward with this.

**Review by Aguncan — APPROVED** [review]
Thanks for very good figure.

**Comment by emmajhudgins** [comment]
> @LunaSare I think creating those 2 cases in the figure sounds great to me.
> 
> * Moving the 'citable data and code' down to a 3 in difficulty and keeping the 'maintaining' data and code higher.
> * Separating out the two seems like a good way to move forward with this.

agreed with this change! especially that we should be encouraging the easy DOI steps.

**Comment by robcrystalornelas** [comment]
@Aariq, Luna plans to make the updates soon. Stay tuned here for updated figures.

**Review by Aariq — APPROVED** [review]
Looks great!

**Pull request merged**
