### PR TITLE
added paragraph on using GitHub for website

### PR DESCRIPTION
**Pull request by robcrystalornelas**
In this PR, I added some text (and citations) for the use case about using GitHub to build a website.

### CODE REVIEW

**Review by BrandonEdwards — APPROVED** [review]
Nice! Do you think it makes sense to also add a brief blurb about the ease of using your own domain name for the websites too? Maybe it's not that big of a deal anymore since the "x.github.io" websites are becoming more or less common, but GH pages still does make it fairly easy to use your own custom domain (e.g., brandonedwards.ca) while hosting with Github. Useful for Lab websites that want to maybe have a quick website name?

I don't know, could be irrelevant to add this, and I've gone ahead and approved these changes regardless. But if you do want to add a blurb into this PR, go ahead! Otherwise these can just be merged.

**Review by Aariq — APPROVED** [review]

**Comment by emmajhudgins** [comment]
@robcrystalornelas I resolved our conflicts but we can definitely further consolidate our separate parts into one paragraph

**Comment by Aguncan** [comment]
image
I need write access for merging. Is the problem is still ongoing? or Do I something wrong?

**Comment by emmajhudgins** [comment]
> image
> I need write access for merging. Is the problem is still ongoing? or Do I something wrong?

I believe I just gave you access by the process outlined in #72 - let me know if it worked!

**Pull request merged**
