### PR TITLE
Edited version of my affiliation

### PR DESCRIPTION
**Pull request by shafieisabets**
No comma anymore at the beginning of the sentence.

### CODE REVIEW

**Comment by katherinehebert** [comment]
Hi! It looks like we worked on this at the same time haha - I corrected your affiliation line before merging #61, so we're all good to go! Your affiliation should be in the [manuscript](https://sortee-github-hackathon.github.io/manuscript/v/latest/index.html) now.

If you're ok with it, I will close this PR without merging, since the information has already been merged into the manuscript.

**Comment by shafieisabets** [comment]
> Hi! It looks like we worked on this at the same time haha - I corrected your affiliation line before merging #61, so we're all good to go! Your affiliation should be in the [manuscript](https://sortee-github-hackathon.github.io/manuscript/v/latest/index.html) now.
> 
> If you're ok with it, I will close this PR without merging, since the information has already been merged into the manuscript.

Yess Katherine! So  I think we did a great job today. I have learned a lot! Shall we also do the same section of the paper? A kind of developing coordination. ;)

**Comment by shafieisabets** [comment]
> > Hi! It looks like we worked on this at the same time haha - I corrected your affiliation line before merging #61, so we're all good to go! Your affiliation should be in the [manuscript](https://sortee-github-hackathon.github.io/manuscript/v/latest/index.html) now.
> > If you're ok with it, I will close this PR without merging, since the information has already been merged into the manuscript.
> 
> Yess Katherine! So I think we did a great job today. I have learned a lot! Shall we also do the same section of the paper? A kind of developing coordination. ;)

Yes, please! I think I got an email from manubot that my change request was not successful.

**Comment by shafieisabets** [comment]
> > > Hi! It looks like we worked on this at the same time haha - I corrected your affiliation line before merging #61, so we're all good to go! Your affiliation should be in the [manuscript](https://sortee-github-hackathon.github.io/manuscript/v/latest/index.html) now.
> > > If you're ok with it, I will close this PR without merging, since the information has already been merged into the manuscript.
> > 
> > 
> > Yess Katherine! So I think we did a great job today. I have learned a lot! Shall we also do the same section of the paper? A kind of developing coordination. ;)
> 
> Yes, please! I think I got an email from manubot that my change request was not successful.

I also added my Twitter handle finally.

**Pull request closed without merging**
