### PR TITLE
R tables and figures workflow

### PR DESCRIPTION
**Pull request by Aariq**
Try using `flextable` to create box 2 table as an image, then integrating into Introduction (for now).  Eventually I'll add something to the gh action to run the scripts in `../R/` before building the manuscript so figures and tables are up to date.

### CODE REVIEW

**Comment by Aariq** [comment]
I didn't end up setting up a gh action to run R scripts because it would probably involve setting up `renv` or the like for package management, and wasn't sure if that might be overkill.  I don't know how many co-authors are going to want to generate figures or tables in R.  For now, anyone editing things in `R/` can just remember to run scripts before committing changes maybe?

**Comment by robcrystalornelas** [comment]
I'm going to add @pedrohbraga as reviewer since I think his perspective on the actions will be helpful.

**Comment by Aariq** [comment]
It would also be good to talk about in today's meeting.  If a lot of people are planning on using R for figures or tables, then getting github actions set up might be more helpful/important.

**Comment by Aariq** [comment]
In today's meeting we decided to just merge this without a corresponding github action for now.  Several people are planning on using R to make figures or tables, so I'll consider a separate PR to modify or add a github action to run scripts before manubot builds.

**Review by robcrystalornelas — APPROVED** [review]
@Aariq thanks for the additions here! going to approve and merge as we discussed during our Feb meeting.

**Pull request merged**
