### PR TITLE
Scatterblob edits

### PR DESCRIPTION
**Pull request by LunaSare**
Addressing https://github.com/SORTEE-Github-Hackathon/manuscript/issues/198

~Still need to address this one https://github.com/SORTEE-Github-Hackathon/manuscript/issues/160~
And also finished tidying up methods for https://github.com/SORTEE-Github-Hackathon/manuscript/issues/160

### CODE REVIEW

**Comment by Aariq** [comment]
Is Viridis turbo a color blind friendly palette? Not super important since color and y-value are redundant, but probably a good idea to pick something grayscale and colorblind friendly

**Comment by Aariq** [comment]
Looks good.  One minor comment: the figure caption says "degree of collaborativity" and the figure axis says "degree of collaborativeness".  I'm not 100% sure which one of those is correct, but they should probably be the same.

**Comment by Aariq** [comment]
Actually, one other comment.  On the y-axis, what do you think about having fewer labels?  E.g. only Beginner, intermediate, advanced?  Readers can interpolate between those labels I think?

**Comment by LunaSare** [comment]
Awesome @Aariq, thanks for the comments!

> Is Viridis turbo a color blind friendly palette? 
Viridis turbo is [color blind friendly, and grayscale friendly](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html) yay! 💃 

> the figure caption says "degree of collaborativity" and the figure axis says "degree of collaborativeness". I'm not 100% sure which one of those is correct, but they should probably be the same.
I am also not sure which one would be correct. looked for both word in the dictionary, and none seem to be in there :/
However, collaborativeness does appear in google searches and webpages used in the sense we want, whereas collaborativity is more often used as name for brands and companies. Maybe we could simply use the word collaboration, as in "degree of collaboration" or "extent of collaboration"?

> On the y-axis, what do you think about having fewer labels? E.g. only Beginner, intermediate, advanced? Readers can interpolate between those labels I think?
I wouldn't mind! It would probably look less cluttered. What do others think?

**Comment by robcrystalornelas** [comment]
Really awesome updates on this @LunaSare!! Will respond to @Aariq and your comments in thread above.

**Comment by LunaSare** [comment]
Thanks everyone! Finally addressed the remaining few edits suggested by @robcrystalornelas, @Aariq and @kaitlyngaynor https://github.com/SORTEE-Github-Hackathon/manuscript/issues/198

> 1. The viridis turbo one is my preferred visualization. I like that color scheme.

Figures with that color scheme are tagged "viridis-turbo"

> 2. I like using collaboration instead as in "degree of collaboration"

Fixed ✅ 

> 3. Fewer labels on the y-axis works for me too, I think there's a lot to read along the right side of the diagram so having fewer y-axis ticks makes that side less to read through.

Done ✔️ 

> 4. Looking through your examples, I think I like this version pasted below with the bars kind of closer together rather than having some of the very advances uses way up top.

That version corresponds to figure `content/images/scatterblob_1-viridis-turbo.png`

image

**Comment by LunaSare** [comment]
I also cleaned the scatterblob.Rmd some, and rendered it as pdf `R/scatterblob.pdf`, so we can use it as supplementary data, as suggested by @Aariq https://github.com/SORTEE-Github-Hackathon/manuscript/issues/160

**Comment by robcrystalornelas** [comment]
Nice @LunaSare 🎉  I will for sure review tomorrow. I really appreciate all of your work on getting this figure together and revised.

**Review by Aariq — APPROVED** [review]

**Pull request merged**
