### PR TITLE
Update 05.use-cases-c.md

### PR DESCRIPTION
**Pull request by DrMattG**
Response to most comments on hypothesis.io Big-Picture. 

* I have not touched the last section but think the comment about merging this section is a good idea
* I have also not moved the Open Science Discussion section - should this be moved to the top of the use-cases? (see the comment on this section)

### CODE REVIEW

**Comment by robcrystalornelas** [comment]
@BrandonEdwards and @pedrohbraga just mentioning here in case you have time to do review over the next couple of days. Otherwise I'm happy to review!

**Comment by pedrohbraga** [comment]
Hi! I am going to check this in the next two days! I need to meet a deadline for the submission of a revised manuscript and then I will allocate time to this!

**Comment by robcrystalornelas** [comment]
@BrandonEdwards @pedrohbraga I've got a bit of time today, so I'll likely do a quick review of this PR and merge ~ noon PT so that I can let our full group know that the manuscript is ready for edits 😄

**Review by robcrystalornelas — APPROVED** [review]
Thanks for working on this PR @DrMattG !

**Pull request merged**
