### PR TITLE
Reformatting and adding supplementary material

### PR DESCRIPTION
**Pull request by pedrohbraga**
Hi,

This pull request reformats the supplementary material to address R2.2's request to clarify how technical difficulty was assessed (see #283).

@LunaSare, this addresses the discussion we had today. To address, #283, we should clarify and extend the topics included in the inside the Appendix S1.1. in this new document I included here `Supp_Info_1.Rmd`. A good part of the information is there (although there are portions that need to be made clear), but it needs to be made into something closer to a publication-quality method. Please let me know what you think and do not hesitate to ask for help on this part. I associated the issue to this PR and this branch, which will automatically close once resolved.

**Request for all: This pull request and its branch are a work in progress. Please do not close or merge it before @LunaSare names and tags reviewers here.**

### CODE REVIEW

**Comment by emmajhudgins** [comment]
whats the status on this component? anything i can do to help?

**Comment by katherinehebert** [comment]
I can also help with this if needed!

**Comment by pedrohbraga** [comment]
Hi,

I will take your offer for help. @katherinehebert mentioned to me she could probably take a look into this in the next couple of days. 

I advanced this a little bit today. I will focus now on adding the lines to the response letter, sending a message to the journal requesting 7 to 10 more days, and writing a message to send to all coauthors.

I will keep you posted and should be able to come back to this if you are unavailable to advance the supplementary material.

**Comment by pedrohbraga** [comment]
A couple of suggestions:

Appendix S1.2 can be made a bit more concise. For instance, we can comment out or remove the attempts for different colour themes, the plot that is not the final figure, and any unnecessary code chunk output. 

Some of the descriptions of the indices can also be moved from Appendix S1.2 can also be moved into Appendix S1.1.

Finally, the data that is in the online spreadsheets should probably become tables (extra unnecessary stuff, such as notes, could be dropped from it)

**Comment by katherinehebert** [comment]
Commit [d354de3](https://github.com/SORTEE-Github-Hackathon/manuscript/pull/298/commits/d354de346629875c73fe731879a9a5378afe1038) addresses the suggestions above, though some more streamlining could probably be done if needed. Changes are also described in the commit description, but essentially:

- Appendix S1.2 was made more concise, and unneeded parts of the code were removed (mainly, the exercise in colour choices and the figures that were not our final Figure 2).
- Moved the descriptions of the indices from Appendix S1.2 into S1.1. Because I didn't participate in those discussions, it would be great if someone could reread the methodology and confirm that my edits make sense. There is also a pre-existing paragraph I put in italics because I wasn't sure we used 1 to 10 to rate the degree of collaboration (but again, I don't really know since I wasn't there).
- Not sure if this is what was suggested, but I haven't put the data tables into tables in the document itself - we could do this as a next step if it is needed! However, all the datasets' names and paths in the GitHub repo are mentioned in the text, and the links to the Google Sheets are noted in the document as well.

Hope this helps!!

**Comment by pedrohbraga** [comment]
Thank you so much, @katherinehebert !!!  I made minor changes to the code and text to remove the laboratory notebook use case.

**Comment by katherinehebert** [comment]
Hey @pedrohbraga ! Just a clarification for adding the data as a table - are you referring to the spreadsheet with the difficulty metrics (the scatterblob dataset), and printing it in the document with `kable`?

**Comment by pedrohbraga** [comment]
@katherinehebert, yes! I have just seen your last update and it seems great! I will just add a description to Table 1, and merge these changes to `main`! I think all is good now!

**Pull request merged**
