### PR TITLE
I just added my info

### PR DESCRIPTION
**Pull request by shafieisabets**

### CODE REVIEW

**Review by shafieisabets — COMMENTED** [review]
I just received an error email from manubut!
"Manubot: All jobs have failed"

**Comment by robcrystalornelas** [comment]
No worries, @shafieisabets! We'll get this figured out in today's meeting 👍🏻

**Comment by katherinehebert** [comment]
Hi Saeed! I think the check failed because line 82 is not aligned, and .yaml files are strict about alignment. Could you try to remove the spaces at the beginning of line 82, so the text lines up with the other entries (so it looks like Emma's line 75)? This might work! :)

**Comment by shafieisabets** [comment]
Cool Katherine! Thanks, @Rob.
line 82 is now aligned., I hope it does work. ;)

**Comment by katherinehebert** [comment]
Oh no! Now it seems to have failed because of line 89 starting with a comma. Moving the comma to the end of line 88 should work. We're close!! :)

**Review by katherinehebert — APPROVED** [review]
It's good to go now!

**Comment by shafieisabets** [comment]
Cool! Good to know I am kind of learning the way of writing and working here. :)

**Comment by katherinehebert** [comment]
Absolutely!! It definitely takes some getting used to! :)

**Pull request merged**
