### PR TITLE
Repo to repository and fixed a typo

### LINKED ISSUE #216: Convert "repo" to "repositories" in manuscript
@fhillemann brought up question of whether we want to use "repo" in manuscript, or just "repository" throughout. What do you all think? If so, we'll use this issue since a PR will need to address each file of the manuscript.

### PR DESCRIPTION
**Pull request by robcrystalornelas**
I switch the last couple of mentions of "repo" to "repository" and also fixed a typo in one of the figure captions. Closes #216

### CODE REVIEW

**Comment by Aariq** [comment]
`10.roles_table.md` and `11.comparison_table.md` are generated from .Rmd files in `R/` from .csv files `data/collaborator_roles.csv` and `data/comparison_table_raw.csv`.  The spelling should probably be changed in the .csv files and the .Rmd files rendered.

It's set up this way because I found it impossibly difficult to edit markdown tables with long text strings in the cells by hand.

**Comment by robcrystalornelas** [comment]
I see, @Aariq, do you think you could make these changes to the right rmd and csv files as part of this PR?

**Comment by Aariq** [comment]
Yeah, I can take over this PR.  I'll get to it next week.

**Comment by Aariq** [comment]
Should be good to go now

**Comment by robcrystalornelas** [comment]
@pedrohbraga or @DrMattG Can you review the changes @Aariq made. Since I'm PR author, I'm not able to review. Thanks!

**Review by DrMattG — APPROVED** [review]

**Pull request merged**
