### PR TITLE
Box 1 update accordingly. except few comments

### PR DESCRIPTION
**Pull request by shafieisabets**
Box 1 update accordingly. except few comments which are not solved yet.

### CODE REVIEW

**Comment by robcrystalornelas** [comment]
@shafieisabets changes to table 1 look great. It looks like there's a new file in here called comparisons_table.html. Did you make any changes to that table? If so, please make them to the file 11.comparison_table.md rather than 11.comparison_table.**html**

If you didn't make any changes to that file, I can delete that one.

**Comment by shafieisabets** [comment]
Also , I can see some comments in Box 2 for instance " 8. If you are an educator, include lectures on reproducibility and tools for creating reproducible workflows in your curricula." 
I can see in full-group- 1 there is a comment on "your" to be changed into "the" given by [dgomes50](https://hypothes.is/u/acct%3Adgomes50%40hypothes.is) and then after that [Matt_Grainger](https://hypothes.is/u/acct%3AMatt_Grainger%40hypothes.is) commented "done" but when I see on the final version of the manuscript in Rstudio in the file called [06.discussion-a.md](http://06.discussion-a.md/) I can see still nothing changes yet.  Does that mean I am using an old version of the manuscript in R? But the thing is I always update my repo before starting to edit. Could you please double-check this instance?
Kind regards
Saeed

**Comment by shafieisabets** [comment]
No worries @DrMattG I will go though it once again. It also happens a lot to me. For me it is still a kind of not easy and tricky software to write a manuscript. :)

**Comment by shafieisabets** [comment]
I just have changed the most of comments accordingly and made pull requests. Although still there are some comments not adjustments in Box 1,2 , picture 1 and 2 and table;e 1 and 2.

**Review by robcrystalornelas — APPROVED** [review]
Thanks so much for making these updates @shafieisabets. I'm approving and then merging

**Pull request merged**
