### PR TITLE
Contributor roles table

### PR DESCRIPTION
**Pull request by Aariq**
This incorporates the changes suggested by @kaitlyngaynor in #131 and builds upon it.  The resulting table is still fairly sparse and I'd love suggestions for additional ways these features can be used.  Also, I'm not certain I like the features "GitHub repo" and "README.  They both just referring to the GitHub web interface for a repo as a whole, I think.  The landing page of a GitHub repo is useful because there are ways to edit and view documents without setting anything up and things like the automatic rendering of README.md.  If anyone can think of a better name for these columns, I'm open to suggestions.  

Role descriptions are in the table caption and feature descriptions are in Box 1

roles
.

### CODE REVIEW

**Comment by Aariq** [comment]
I realized that in order for automatic table references to work with pandoc, tables need to actually be markdown tables, and not images of tables.  I added a commit that attempts to generate a .md file from .Rmd with the markdown table.  Could revert and use the image version with manual citation.

**Comment by Aariq** [comment]
I'm marking this as a draft until I have time to figure out how Manubot and table citations work, but would still appreciate feedback on the table content and format.

**Comment by Aariq** [comment]
I got manubot working locally and confirmed that you can't trick it into treating images as table references.  I've now included some examples of how to do in-text citations of figures and tables.

**Review by robcrystalornelas — APPROVED** [review]
@Aariq here are my proposals for potential additions to the Role table. I've approved here just in case you rather I merge what we have since the editing group is meeting tomorrow.

co-author//Issue: Propose task to be completed by code maintainer
code contributor//github repo: version control code and invite collaborators
code contributor//discussion: invite feedback on topics related to github repository
code contributor//fork: contribute changes to other repositories you use in workflow
code contributor//github pages: promote work through easy-to-navigate website

code reviewer//github repo: centralized place to find all code related to project
code reviewer//discussion: provide input on topics about content in repository
code reviewer//github pages: proofread material posted on GitHub Pages website

community//GitHub repo: Reuse code shared in repo, identify collaborators
community//issue: propose changes to code, ask for new features, identify bugs
community//pull request: actively contribute to code in repo


Also, not sure if we want to fill in empty cells with N/As?

**Comment by Aariq** [comment]
> code contributor//github repo: version control code and invite collaborators
> code contributor//discussion: invite feedback on topics related to github repository

Can you elaborate on these?

> community//pull request: actively contribute to code in repo
I think at this point you'd have become a code-contributor

**Pull request merged**
