### PR TITLE
Response to Reviewers

### PR DESCRIPTION
**Pull request by Aariq**
This PR makes some improvments on the response to reviewers document.  I've re-formatted it a little (e.g. to make reviewer comments blockquotes and responses regular text) and added the ability to cross-reference sections, which I find super helpful in these responses.  I also copied over some responses that were in isssues or PRs but didn't make it into this document.

This PR:

1. Changes the response to reviewers document from .Rmd to .Qmd to allow cross-referencing sections
2. Gives each reviewer comment its own H4 section with a cross-ref-able section ID (e.g. #sec-R1.1) that can be referenced with, e.g., `@sec-R1.1`
3. Puts reviewer/editor text in blockquote
4. Adds responses from issues and PRs as well as some new responses.
5. Converts the cover letter to .Qmd also so that the github action can be greatly simplified and no longer use R or R packages

### CODE REVIEW

**Comment by Aariq** [comment]
Rendered HTML version of response to reviewers (draft): https://sortee-github-hackathon.github.io/manuscript/editorial-communication/response-to-the-reviewers.html

**Comment by emmajhudgins** [comment]
awesome! great to know that Qmd has extra functionality. I assume you want Pedro to take a look otherwise i'd approve

**Comment by pedrohbraga** [comment]
Hi, @Aariq. Thank you for these edits (and Happy New Year!). 

I will be working directly on this branch today and tomorrow. I will let you know once I am done.

**Comment by Aariq** [comment]
Any other additions to this @pedrohbraga?

**Comment by Aariq** [comment]
Should we merge this so that other PRs can edit it as they respond to reviewers?

**Pull request merged**
