### PR TITLE
add text to use cases on organizations and educational materials

### PR DESCRIPTION
**Pull request by colebrookson**
added text in these two sections, still much more to talk about in both, but kept it short for the time being

### CODE REVIEW

**Review by emmajhudgins — APPROVED** [review]
looks great!

**Comment by pedrohbraga** [comment]
Hi, @colebrookson and @emmajhudgins ! The addition to the manuscript looks great! However, as you can see, the branch cannot be merged because there is a little conflict. It looks quite simple to solve it, however, can we leave it as-is for tomorrow's meeting?

@robcrystalornelas wanted to review and practice on the pull requests that we have been using and this would be a good hands-on example for us to use tomorrow!

**Comment by colebrookson** [comment]
Hiya!! @emmajhudgins @pedrohbraga @robcrystalornelas  Sure! Unfortunately I won't be able to make it tomorrow (committee meeting ugh), but unless you need me specifically to resolve the conflicts, that's totally fine by me :+1:

**Comment by emmajhudgins** [comment]
oh darn! Clearly I need the demo tomorrow because I thought I was doing this right!

**Comment by robcrystalornelas** [comment]
No worries @emmajhudgins I could use one too :) and I think it's great to have an example pull request we can discuss tomorrow.

@colebrookson good luck with the committee meeting 👍🏻

**Comment by pedrohbraga** [comment]
@emmajhudgins not an issue at all from your end! You got it right! 

The reviewing and the merging processes are separate. Only after reviewing and approving the changes one will know if there is a conflict between the branch in question and the `main` repository.

image

**Comment by pedrohbraga** [comment]
Hi, @colebrookson ! We chatted about the conflict during the meeting! It happened because you and @katherinehebert made pull requests changing the same sentence, with her pull request being merged to `main` prior to yours.

This may happen once in a while and the way to solve it is to click on "Resolve conflict". A text editor will open showing you where the conflict is, with both the text from the pull request and the text that is within the `main` branch. One has to carefully read the conflicted region and resolve the conflict by adjusting and leaving only the text that should be merged.

Once all conflicts are resolved, they are committed and become part of the pull request, which should then be capable of being merged without issues.

I resolve the conflict! However, there is a little extra issue that I will write in an upcoming comment!

**Comment by colebrookson** [comment]
Cool! Sorry, what was the other small issue? Or did you open a separate issue for it?

**Comment by pedrohbraga** [comment]
Hi, @colebrookson! The issue was with sentences not being separated by returns, as I commented above. I have already corrected this issue in the latest commits I pushed to this pull-request. I am merging it now! Have a good rest of the day!!

**Pull request merged**
