### PR TITLE
Update 06.discussion-a.md

### PR DESCRIPTION
**Pull request by emmajhudgins**
reformatted 10 tips section as a table. Apologies, this formatting doesn't allow >1 line per table row entry so I had to delete the newlines!

### CODE REVIEW

**Comment by Aguncan** [comment]
Hi Emma, It is looking great. Thank you for the efforts. I want to ask a question. I have changed and reviewed some of the tips in my previous PR #128. You have approved that PR. However, I am waiting review from @robcrystalornelas for the changes in [content/04.use-cases-b.md](https://github.com/SORTEE-Github-Hackathon/manuscript/pull/128/files#diff-588a9efac95f9443e2a040b5a9a8b26f1b2b4c50ea6a1a6a1d00fa48b1333483) before merging. Will my changes and reviews in Tips section conflict with this PR, after approving and merging this PR?

**Comment by emmajhudgins** [comment]
Hi Ali! I think they'll conflict but will be relatively easy to solve. I don't mind doing this down the line once @robcrystalornelas is done his review of your PR.

**Comment by emmajhudgins** [comment]
yep that was it @robcrystalornelas! @Aguncan , it should be good to go now.

**Comment by Aguncan** [comment]
LOL! You are so fast. I can not catch you and your messages.

**Review by Aguncan — APPROVED** [review]

**Pull request merged**
